# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 02:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0002_auto_20170626_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='review',
            name='posted_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
