# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0007_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_score',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
