# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0008_review_star_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_score',
            field=models.CharField(max_length=100000),
        ),
    ]
