# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0010_auto_20170627_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valley_green_landscape.GalleryContainer')),
            ],
        ),
    ]
