# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0013_gallerycontainer_badge_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycontainer',
            name='badge_code',
            field=models.CharField(max_length=10000),
        ),
    ]
