# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0014_auto_20170714_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
