# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0015_review_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='truncated_text',
            field=models.CharField(default='Truncated Text', max_length=300),
            preserve_default=False,
        ),
    ]
