# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0016_review_truncated_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='truncated_text',
        ),
    ]
