# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0017_remove_review_truncated_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_key', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='review_key',
            field=models.CharField(default='NO KEY', max_length=6),
        ),
    ]
