# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0018_auto_20170724_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='container',
        ),
        migrations.DeleteModel(
            name='GalleryContainer',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
