# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0020_auto_20170724_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceUser',
            new_name='User',
        ),
    ]
