# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0021_auto_20170724_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valley_green_landscape.User'),
        ),
    ]
