# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley_green_landscape', '0024_auto_20170807_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
